# Generated by Django 4.0.4 on 2022-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=100)),
                ('company_group', models.CharField(max_length=100)),
                ('company_industry', models.CharField(max_length=100)),
                ('face_value', models.FloatField()),
                ('isin_number', models.CharField(max_length=100)),
            ],
            options={
                'get_latest_by': 'company_id',
            },
        ),
    ]
