# Generated by Django 4.0.4 on 2022-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='face_value',
            field=models.CharField(max_length=10),
        ),
    ]
