# Generated by Django 4.0.4 on 2022-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_alter_company_face_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
