#!/bin/bash

PROJECT=/home/himanshu/webapps/stockdata
BRANCH=main

echo "Project is $PROJECT with branch $BRANCH"

# exit if anything fails
set -e

echo "Checking out new code"
mkdir -p $PROJECT
git --work-tree=$PROJECT checkout $BRANCH -f

echo "Running deploy/deploy.sh"
cd $PROJECT
bash ~/webapps/stockdata/deploy/deploy.sh
